### ISSUE TITLE
UIROOT节点动态创建反而更方便

### ISSUE THREAD

**Issue by as01788** [kirikayakazuto/CocosCreator_UIFrameWork#4]
public static getInstance(): UIManager {
        if(this.instance == null) {
            // this.instance = cc.find(SysDefine.SYS_UIROOT_NAME).addComponent<UIManager>(this);
            let newNode = new cc.Node('UIROOT');
            newNode.addChild(new cc.Node('SceneBase'));
            newNode.addChild(new cc.Node('FixedUI'));
            newNode.addChild(new cc.Node('PopUp'));
            newNode.addChild(new cc.Node('TopTips'));
            newNode.addChild(new cc.Node('UIMaskScript'));
            newNode.addChild(new cc.Node('UIAdaptationScript'));
            newNode.setParent(cc.find("Canvas"));
            this.instance = newNode.addComponent<UIManager>(this);
            cc.director.once(cc.Director.EVENT_AFTER_SCENE_LAUNCH, () => {
                this.instance = null;
            });
        }
        return this.instance;
    }

这样不用手动拖动，至于🔒是只对编辑器有效，对运行中无效

**Comment by kirikayakazuto** [comment]
的确, 代码创建会比较方便, 之前也有过这个想法, 近期会优化一下
