### ISSUE TITLE
MaskPlus扩展带来的点击问题

### ISSUE THREAD

**Issue by LogicCoder** [kirikayakazuto/CocosCreator_UIFrameWork#6]
MaskPlus扩展的多边形会破坏感应区，导致子节点如果是button的话出现点击感应混乱

**Comment by kirikayakazuto** [comment]
maskplus设计之初 就是为了实现不规则按钮, 所以多边形外的区域是无法点击的

**Comment by LogicCoder** [comment]
我测试的结果是很混乱，多边形内很多区域点不动，多边形外反而能响应点击事件

**Comment by kirikayakazuto** [comment]
要不加我qq联系吧, 1099263878, 我这边实测 是没问题的
